// =============================================================================
// SeederLinux v3.0 - Catálogo Oficial de Variáveis
// Baseado no Documento 06 - Catálogo Oficial de Variáveis
// =============================================================================
//
// Categorias (Documento 06):
//   DOMINIO, ARQUIVOS, NAVEGADORES, BRANDING, INVENTARIO, REMOTO,
//   IMPRESSORAS, CERTIFICADOS, REPOSITORIOS, MIRROR, AGENTE,
//   SEGURANCA, INTEGRACOES

export interface VariableCatalogEntry {
  key: string;
  label: string;
  category: string;
  description: string;
  type: 'string' | 'boolean' | 'integer' | 'ip' | 'url' | 'array';
  required: boolean;
  editable: boolean;
  oficial: boolean;
  defaultValue: string;
  exemplo?: string;
  validation?: string | null;
  coreModule?: string | null;
}

export const VARIABLE_CATALOG: VariableCatalogEntry[] = [
  // ===== DOMÍNIO =====
  {
    key: 'DOMINIO',
    label: 'Domínio AD',
    category: 'DOMINIO',
    description: 'Domínio DNS completo da organização (FQDN do Active Directory).',
    type: 'string',
    required: true,
    editable: true,
    oficial: true,
    defaultValue: '',
    exemplo: 'fab.mil.br',
    coreModule: 'Core.Domain',
  },
  {
    key: 'DOMINIO_NETBIOS',
    label: 'Nome NetBIOS',
    category: 'DOMINIO',
    description: 'Nome NetBIOS do domínio (até 15 caracteres).',
    type: 'string',
    required: true,
    editable: true,
    oficial: true,
    defaultValue: '',
    exemplo: 'FAB',
    coreModule: 'Core.Domain',
  },
  {
    key: 'DC_IP',
    label: 'IP do Controlador de Domínio',
    category: 'DOMINIO',
    description: 'Endereço IP do Controlador de Domínio (DC) primário.',
    type: 'ip',
    required: true,
    editable: true,
    oficial: true,
    defaultValue: '',
    exemplo: '10.108.1.10',
    coreModule: 'Core.Domain',
  },
  {
    key: 'DNS_PRIMARIO',
    label: 'DNS Primário',
    category: 'DOMINIO',
    description: 'Endereço IP do servidor DNS primário.',
    type: 'ip',
    required: true,
    editable: true,
    oficial: true,
    defaultValue: '',
    exemplo: '10.108.1.10',
    coreModule: 'Core.Domain',
  },
  {
    key: 'DNS_SECUNDARIO',
    label: 'DNS Secundário',
    category: 'DOMINIO',
    description: 'Endereço IP do servidor DNS secundário.',
    type: 'ip',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    exemplo: '10.108.1.11',
    coreModule: 'Core.Domain',
  },
  {
    key: 'NTP_SERVER',
    label: 'Servidor NTP',
    category: 'DOMINIO',
    description: 'Servidor NTP corporativo para sincronização de relógio.',
    type: 'string',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: 'pool.ntp.org',
    exemplo: 'ntp.fab.mil.br',
    coreModule: 'Core.Domain',
  },
  {
    key: 'OU_PADRAO',
    label: 'OU Padrão',
    category: 'DOMINIO',
    description: 'Unidade Organizacional padrão para criação de computadores no AD.',
    type: 'string',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    exemplo: 'OU=Computadores,DC=fab,DC=mil,DC=br',
    coreModule: 'Core.Domain',
  },
  {
    key: 'GRUPO_ADMIN',
    label: 'Grupo Admin Local',
    category: 'DOMINIO',
    description: 'Grupo AD que possui privilégios administrativos locais.',
    type: 'string',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: 'GG-TI-LINUX',
    exemplo: 'GG-TI-LINUX',
    coreModule: 'Core.Domain',
  },
  {
    key: 'OFFLINE_AUTH_ENABLED',
    label: 'Autenticação Offline',
    category: 'DOMINIO',
    description: 'Habilita autenticação offline com cache de credenciais.',
    type: 'boolean',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: 'true',
    coreModule: 'Core.Domain',
  },

  // ===== ARQUIVOS =====
  {
    key: 'SERVIDOR_ARQUIVOS',
    label: 'Servidor de Arquivos',
    category: 'ARQUIVOS',
    description: 'Nome do servidor de arquivos (CIFS/Samba).',
    type: 'string',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    exemplo: 'filesrv01',
    coreModule: 'Core.Files',
  },
  {
    key: 'COMPARTILHAMENTOS',
    label: 'Compartilhamentos',
    category: 'ARQUIVOS',
    description: 'Lista de compartilhamentos a montar (separados por vírgula).',
    type: 'array',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    exemplo: 'Publico,Administrativo,Tecnico',
    coreModule: 'Core.Files',
  },
  {
    key: 'MOUNT_BASE',
    label: 'Diretório base de montagem',
    category: 'ARQUIVOS',
    description: 'Diretório base onde os compartilhamentos serão montados.',
    type: 'string',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '/mnt',
    coreModule: 'Core.Files',
  },

  // ===== NAVEGADORES =====
  {
    key: 'HOMEPAGE',
    label: 'Página inicial',
    category: 'NAVEGADORES',
    description: 'URL definida como página inicial nos navegadores.',
    type: 'url',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    exemplo: 'https://intranet.fab.mil.br',
    coreModule: 'Core.Browser',
  },
  {
    key: 'PROXY_MODE',
    label: 'Modo do Proxy',
    category: 'NAVEGADORES',
    description: 'Modo de configuração de proxy: NONE, MANUAL ou PAC.',
    type: 'string',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: 'NONE',
    exemplo: 'MANUAL',
    coreModule: 'Core.Browser',
  },
  {
    key: 'PROXY_HTTP',
    label: 'Host do Proxy',
    category: 'NAVEGADORES',
    description: 'Host (ou IP) do proxy HTTP.',
    type: 'string',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    exemplo: 'proxy.intraer',
    coreModule: 'Core.Browser',
  },
  {
    key: 'PROXY_PORTA',
    label: 'Porta do Proxy',
    category: 'NAVEGADORES',
    description: 'Porta TCP do proxy HTTP.',
    type: 'integer',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '3128',
    exemplo: '3128',
    coreModule: 'Core.Browser',
  },
  {
    key: 'PAC_URL',
    label: 'URL do PAC',
    category: 'NAVEGADORES',
    description: 'URL do arquivo PAC (Proxy Auto-Config) quando modo for PAC.',
    type: 'url',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    exemplo: 'http://wpad.intraer/wpad.dat',
    coreModule: 'Core.Browser',
  },
  {
    key: 'NO_PROXY',
    label: 'Exceções de Proxy',
    category: 'NAVEGADORES',
    description: 'Endereços que NÃO devem usar proxy (separados por vírgula).',
    type: 'array',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: 'localhost,127.0.0.1,.intraer',
    exemplo: 'localhost,10.0.0.0/8,*.intraer',
    coreModule: 'Core.Browser',
  },

  // ===== BRANDING =====
  {
    key: 'DISPLAY_NAME',
    label: 'Nome de Exibição',
    category: 'BRANDING',
    description: 'Nome amigável da OM, exibido na interface.',
    type: 'string',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    exemplo: 'Comando da Aeronáutica',
    coreModule: 'Core.Branding',
  },
  {
    key: 'WALLPAPER',
    label: 'Wallpaper',
    category: 'BRANDING',
    description: 'URL da imagem de fundo do desktop.',
    type: 'url',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    coreModule: 'Core.Branding',
  },
  {
    key: 'WALLPAPER_LOGIN',
    label: 'Wallpaper da Tela de Login',
    category: 'BRANDING',
    description: 'URL da imagem de fundo da tela de login.',
    type: 'url',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    coreModule: 'Core.Branding',
  },
  {
    key: 'LOGO',
    label: 'Logo',
    category: 'BRANDING',
    description: 'URL da logomarca da organização.',
    type: 'url',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    coreModule: 'Core.Branding',
  },
  {
    key: 'GREETER_URL',
    label: 'Imagem do Greeter',
    category: 'BRANDING',
    description: 'URL da imagem exibida na tela de autenticação (greeter).',
    type: 'url',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    coreModule: 'Core.Branding',
  },
  {
    key: 'THEME',
    label: 'Tema GTK',
    category: 'BRANDING',
    description: 'Nome do tema GTK aplicado ao desktop.',
    type: 'string',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: 'Mint-Y-Dark',
    exemplo: 'Mint-Y-Dark',
    coreModule: 'Core.Branding',
  },
  {
    key: 'CONKY_PROFILE',
    label: 'Perfil Conky',
    category: 'BRANDING',
    description: 'Perfil institucional do Conky a aplicar.',
    type: 'string',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    coreModule: 'Core.Branding',
  },
  {
    key: 'SHORTCUTS_ENABLED',
    label: 'Atalhos no desktop',
    category: 'BRANDING',
    description: 'Habilita atalhos corporativos no desktop dos usuários.',
    type: 'boolean',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: 'true',
    coreModule: 'Core.Branding',
  },

  // ===== INVENTÁRIO =====
  {
    key: 'OCS_SERVER',
    label: 'Servidor OCS Inventory',
    category: 'INVENTARIO',
    description: 'URL do servidor OCS Inventory NG.',
    type: 'url',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    coreModule: 'Core.Inventory',
  },
  {
    key: 'GLPI_SERVER',
    label: 'Servidor GLPI',
    category: 'INVENTARIO',
    description: 'URL do servidor GLPI.',
    type: 'url',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    coreModule: 'Core.Inventory',
  },
  {
    key: 'INVENTORY_ENABLED',
    label: 'Inventário habilitado',
    category: 'INVENTARIO',
    description: 'Habilita o envio de inventário.',
    type: 'boolean',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: 'true',
    coreModule: 'Core.Inventory',
  },

  // ===== ACESSO REMOTO =====
  {
    key: 'REMOTE_METHOD',
    label: 'Método de acesso remoto',
    category: 'REMOTO',
    description: 'Tecnologia de acesso remoto: RUSTDESK, VNC ou ANYDESK.',
    type: 'string',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: 'RUSTDESK',
    exemplo: 'RUSTDESK',
    coreModule: 'Core.Remote',
  },
  {
    key: 'REMOTE_SERVER',
    label: 'Servidor de acesso remoto',
    category: 'REMOTO',
    description: 'Endereço do servidor relay para acesso remoto.',
    type: 'string',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    exemplo: 'rustdesk.intraer',
    coreModule: 'Core.Remote',
  },

  // ===== IMPRESSORAS =====
  {
    key: 'PRINT_SERVER',
    label: 'Servidor CUPS',
    category: 'IMPRESSORAS',
    description: 'Servidor CUPS corporativo de impressão.',
    type: 'string',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    exemplo: 'cups.intraer',
    coreModule: 'Core.Printers',
  },
  {
    key: 'DEFAULT_PRINTER',
    label: 'Impressora padrão',
    category: 'IMPRESSORAS',
    description: 'Nome da impressora padrão.',
    type: 'string',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    exemplo: 'HP-LASER-01',
    coreModule: 'Core.Printers',
  },
  {
    key: 'PRINTERS',
    label: 'Impressoras disponíveis',
    category: 'IMPRESSORAS',
    description: 'Lista de filas de impressão disponíveis.',
    type: 'array',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    exemplo: 'HP-LASER-01,EPSON-ADM-02',
    coreModule: 'Core.Printers',
  },

  // ===== CERTIFICADOS =====
  {
    key: 'CERTIFICATE_BUNDLE',
    label: 'Bundle de Certificados',
    category: 'CERTIFICADOS',
    description: 'URL do bundle de certificados raiz a instalar.',
    type: 'url',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    coreModule: 'Core.Certificates',
  },
  {
    key: 'CERTIFICATE_AUTO_INSTALL',
    label: 'Instalar certificados automaticamente',
    category: 'CERTIFICADOS',
    description: 'Instala automaticamente o bundle de certificados durante o provisionamento.',
    type: 'boolean',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: 'true',
    coreModule: 'Core.Certificates',
  },

  // ===== REPOSITÓRIOS =====
  {
    key: 'REPOSITORY_MODE',
    label: 'Modo do Repositório',
    category: 'REPOSITORIOS',
    description: 'Modo de operação dos repositórios: PUBLIC, MIRROR, HYBRID ou CUSTOM.',
    type: 'string',
    required: true,
    editable: true,
    oficial: true,
    defaultValue: 'PUBLIC',
    exemplo: 'HYBRID',
    coreModule: 'Core.Repositories',
  },
  {
    key: 'REPOSITORY_URL',
    label: 'URL do Repositório',
    category: 'REPOSITORIOS',
    description: 'URL do repositório personalizado (quando modo for CUSTOM/MIRROR).',
    type: 'url',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    exemplo: 'http://repo.comara.intraer/debian',
    coreModule: 'Core.Repositories',
  },
  {
    key: 'REPOSITORY_FALLBACK',
    label: 'Fallback para Internet',
    category: 'REPOSITORIOS',
    description: 'Permite cair para repositórios públicos caso o mirror local falhe.',
    type: 'boolean',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: 'true',
    coreModule: 'Core.Repositories',
  },
  {
    key: 'REPOSITORY_DISTRO',
    label: 'Distribuição',
    category: 'REPOSITORIOS',
    description: 'Distribuição-alvo: DEBIAN, UBUNTU ou MINT.',
    type: 'string',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: 'DEBIAN',
    coreModule: 'Core.Repositories',
  },

  // ===== MIRROR LOCAL =====
  {
    key: 'MIRROR_ENABLED',
    label: 'Mirror local habilitado',
    category: 'MIRROR',
    description: 'Habilita o mirror local de pacotes.',
    type: 'boolean',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: 'false',
    coreModule: 'Core.Repositories',
  },
  {
    key: 'MIRROR_STORAGE_PATH',
    label: 'Caminho do Mirror',
    category: 'MIRROR',
    description: 'Caminho local onde o mirror armazena os pacotes.',
    type: 'string',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '/opt/seederlinux/mirror',
    coreModule: 'Core.Repositories',
  },
  {
    key: 'MIRROR_DISTROS',
    label: 'Distribuições do Mirror',
    category: 'MIRROR',
    description: 'Lista de distribuições servidas pelo mirror.',
    type: 'array',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    exemplo: 'Debian 12,Ubuntu 24.04,Linux Mint 22',
    coreModule: 'Core.Repositories',
  },
  {
    key: 'MIRROR_SYNC_SCHEDULE',
    label: 'Agenda de Sync',
    category: 'MIRROR',
    description: 'Horário diário de sincronização do mirror (HH:MM).',
    type: 'string',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '02:00',
    coreModule: 'Core.Repositories',
  },
  {
    key: 'MIRROR_WARNING_THRESHOLD',
    label: 'Alerta de espaço livre',
    category: 'MIRROR',
    description: 'Percentual mínimo livre no volume do mirror para emitir alerta.',
    type: 'integer',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '20',
    coreModule: 'Core.Repositories',
  },

  // ===== AGENTE =====
  {
    key: 'AGENT_CHECKIN_INTERVAL',
    label: 'Intervalo de Check-in',
    category: 'AGENTE',
    description: 'Intervalo entre check-ins do agente (em minutos).',
    type: 'integer',
    required: true,
    editable: true,
    oficial: true,
    defaultValue: '15',
    coreModule: 'Core.Inventory',
  },
  {
    key: 'AGENT_AUTO_UPDATE',
    label: 'Auto-update do Agente',
    category: 'AGENTE',
    description: 'Atualiza o agente automaticamente quando há nova versão.',
    type: 'boolean',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: 'true',
    coreModule: 'Core.Inventory',
  },
  {
    key: 'AGENT_ALLOW_REMOTE_EXECUTION',
    label: 'Permite execução remota',
    category: 'AGENTE',
    description: 'Permite que o agente execute scripts remotos enviados pelo Hub.',
    type: 'boolean',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: 'false',
    coreModule: 'Core.Inventory',
  },

  // ===== SEGURANÇA =====
  {
    key: 'SESSION_TIMEOUT',
    label: 'Timeout de sessão',
    category: 'SEGURANCA',
    description: 'Tempo máximo de inatividade antes de bloquear a sessão (minutos).',
    type: 'integer',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '60',
    coreModule: 'Core.Security',
  },
  {
    key: 'JWT_EXPIRATION',
    label: 'Expiração do JWT',
    category: 'SEGURANCA',
    description: 'Tempo de validade dos tokens JWT (segundos).',
    type: 'integer',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '3600',
    coreModule: 'Core.Security',
  },
  {
    key: 'PASSWORD_MIN_LENGTH',
    label: 'Tamanho mínimo da senha',
    category: 'SEGURANCA',
    description: 'Tamanho mínimo exigido para senhas.',
    type: 'integer',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '12',
    coreModule: 'Core.Security',
  },
  {
    key: 'AUDIT_ENABLED',
    label: 'Auditoria habilitada',
    category: 'SEGURANCA',
    description: 'Habilita os registros de auditoria do sistema.',
    type: 'boolean',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: 'true',
    coreModule: 'Core.Security',
  },

  // ===== INTEGRAÇÕES FUTURAS =====
  {
    key: 'NEXTCLOUD_URL',
    label: 'Nextcloud',
    category: 'INTEGRACOES',
    description: 'URL do servidor Nextcloud.',
    type: 'url',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    coreModule: 'Core.Integrations',
  },
  {
    key: 'ONLYOFFICE_URL',
    label: 'OnlyOffice',
    category: 'INTEGRACOES',
    description: 'URL do servidor OnlyOffice.',
    type: 'url',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    coreModule: 'Core.Integrations',
  },
  {
    key: 'ZABBIX_URL',
    label: 'Zabbix',
    category: 'INTEGRACOES',
    description: 'URL do servidor Zabbix para monitoramento.',
    type: 'url',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    coreModule: 'Core.Integrations',
  },
  {
    key: 'GRAFANA_URL',
    label: 'Grafana',
    category: 'INTEGRACOES',
    description: 'URL do servidor Grafana.',
    type: 'url',
    required: false,
    editable: true,
    oficial: true,
    defaultValue: '',
    coreModule: 'Core.Integrations',
  },
];

/**
 * Chaves obrigatórias automaticamente criadas para cada nova OM
 * (Documento 06, seção 16 - Variáveis Obrigatórias Criadas Automaticamente)
 */
export const MANDATORY_KEYS = [
  'DOMINIO',
  'DOMINIO_NETBIOS',
  'DC_IP',
  'DNS_PRIMARIO',
  'HOMEPAGE',
  'DISPLAY_NAME',
  'REPOSITORY_MODE',
  'OFFLINE_AUTH_ENABLED',
  'AGENT_CHECKIN_INTERVAL',
] as const;
